import { deriveSeed } from '../procedural/random.ts';
import type { InfiniteWorld } from './world.ts';
import type { LifeCandidate } from './life-origin.ts';
import type { ItemId, Point, NpcRole } from './types.ts';
import { civilizationFor, type CivilizationProfile } from './civilization.ts';
import { STICHOS_CLIMATE_SEED } from './ecology.ts';

export interface PersonalRelationship {
  npcId: string;
  name: string;
  role: string;
  clan: number;
  stance: 'ally' | 'witness' | 'rival';
  reason: string;
  /** The resident's own account, distinct from the notebook's third-person history. */
  account: string;
  target: Point;
}
export interface PersonalStoryPlan {
  id: string;
  title: string;
  subtitle: string;
  worldContext: string;
  history: { age: number; title: string; text: string }[];
  relationships: PersonalRelationship[];
  debt: {
    item: ItemId;
    itemName: string;
    required: number;
    recipient: PersonalRelationship;
    title: string;
    reason: string;
  };
  case: { kind: string; title: string; cause: string; stakes: string; outcome: string };
  reward: { coins: number; xp: number };
  commissionGoal: number;
  signal: Point & { id: string; name: string };
  mystery: string;
  purpose: string;
}
export interface PersonalStoryRecord {
  bodyId: string;
  baselineCommissions: number;
  repaid: boolean;
  trusted: string | null;
  aligned: boolean;
  /** People whose account was actually heard, rather than merely seen nearby. */
  heard?: string[];
}
export interface PersonalStoriesState {
  version: 1;
  records: PersonalStoryRecord[];
}
export interface PersonalStoryView
  extends Omit<PersonalStoryPlan, 'relationships' | 'commissionGoal'> {
  relationships: (PersonalRelationship & { met: boolean; heard: boolean; trusted: boolean })[];
  obligations: {
    id: string;
    title: string;
    description: string;
    target: Point;
    progress: number;
    goal: number;
    complete: boolean;
  }[];
  complete: boolean;
}
const distance = (a: Point, b: Point) => Math.hypot(a.x - b.x, a.y - b.y);

/** Story context is independent of terrain revisions; old worlds keep their established culture. */
export function lifeCultureFor(world: InfiniteWorld): CivilizationProfile {
  if (world.civilization) return world.civilization;
  const culture = civilizationFor(STICHOS_CLIMATE_SEED);
  culture.factions = world.clans.map((clan) => ({ ...clan }));
  return culture;
}

/** The life is composed from actual households, professions and residents generated by this world. */
export function generatePersonalStory(
  world: InfiniteWorld,
  life: LifeCandidate,
): PersonalStoryPlan {
  const profile = lifeCultureFor(world);
  const seed = deriveSeed(world.seed, 'v4-personal-history', life.id, life.index);
  const cases = [
    {
      kind: 'shop-audit',
      title: 'The inventory that does not add up',
      stakes: 'the right to keep an inherited workshop open',
      delivery: 'Reconcile the missing stock',
      reason: 'Replace the documented shortfall so the workshop can remain open during its audit.',
      outcome:
        'The audit recognizes an independent workshop whose ownership can no longer be reassigned in secret.',
    },
    {
      kind: 'ration-sabotage',
      title: 'A shortage with a beneficiary',
      stakes: 'a neighborhood supply allotment',
      delivery: 'Keep the allotment alive',
      reason: 'Deliver the emergency replacement while the missing allotment is investigated.',
      outcome:
        'The missing allotment is traced to its beneficiary and the neighborhood gains a witnessed supply account.',
    },
    {
      kind: 'missing-courier',
      title: 'The parcel that arrived twice',
      stakes: 'a courier contract signed by this household',
      delivery: 'Make good on the courier bond',
      reason:
        'Deposit replacement supplies against the disputed courier bond before its claim expires.',
      outcome:
        'The courier record separates the real consignment from its duplicate and closes the household’s liability.',
    },
    {
      kind: 'land-dispute',
      title: 'Two claims to one address',
      stakes: 'the land under this resident’s home',
      delivery: 'Secure a public hearing',
      reason: 'Contribute the required supplies to keep the land claim under public review.',
      outcome:
        'The address receives a witnessed title and the rival claim remains visible instead of silently replacing it.',
    },
    {
      kind: 'broken-broadcast',
      title: 'The warning no one received',
      stakes: 'an emergency warning suppressed before transmission',
      delivery: 'Support the stranded station',
      reason:
        'Supply the station’s caretaker while the interrupted warning and its operators are examined.',
      outcome:
        'The original warning reaches an independent receiver with the suppressed interval attached.',
    },
    {
      kind: 'lost-research',
      title: 'A discovery without its author',
      stakes: 'research credited to someone who did not perform it',
      delivery: 'Reconstruct the sample chain',
      reason:
        'Deliver the materials that let a witness reconstruct the experiment’s chain of custody.',
      outcome:
        'The research acquires a verifiable chain of custody, including the work of the displaced author.',
    },
    {
      kind: 'stolen-identity',
      title: 'The debts of a second self',
      stakes: 'contracts issued through a copy of this resident’s identity',
      delivery: 'Protect the first claimant',
      reason:
        'Help the first person harmed by the duplicate contracts while the false identity is traced.',
      outcome:
        'The duplicate contracts are isolated from this household and the first independent identity record survives.',
    },
  ];
  const roleBias: Record<NpcRole, number> = {
    merchant: 0,
    botanist: 1,
    pilgrim: 2,
    refugee: 3,
    engineer: 4,
    archivist: 5,
    guard: 6,
    raider: 2,
  };
  const hook = cases[(seed + roleBias[life.profession]) % cases.length];
  const causes =
    profile.axes.technology > 0.75
      ? [
          'a copied access signature',
          'a swapped relay shard',
          'a falsified memory timestamp',
          'a diverted maintenance drone',
        ]
      : profile.axes.technology > 0.5
        ? [
            'a re-punched machine register',
            'a rewired relay contact',
            'a forged inspection plate',
            'a missing shipment seal',
          ]
        : [
            'a recut household seal',
            'a replaced ledger folio',
            'an oath recorded under the wrong name',
            'a boundary mark moved overnight',
          ];
  const cause = causes[(seed >>> 19) % causes.length];
  const motive =
    profile.axes.scarcity > 0.65
      ? 'secure a scarce supply before its neighbors can claim it'
      : profile.axes.collectivism > 0.6
        ? 'turn a common holding into a private privilege'
        : 'transfer a private obligation onto an unprotected household';
  const caseProfile = {
    kind: hook.kind,
    title: hook.title,
    stakes: hook.stakes,
    cause,
    outcome: hook.outcome,
  };
  const towns = world
    .settlementsAround(life.settlement.x, life.settlement.y, 680)
    .sort((a, b) => distance(a, life.settlement) - distance(b, life.settlement))
    .slice(0, 4);
  const people = new Map(
    towns
      .flatMap((t) => world.npcsAround(t.x, t.y, t.radius + 1))
      .filter((n) => !n.hostile && n.id !== life.id)
      .map((n) => [n.id, n]),
  );
  const used = new Set<string>();
  const choose = (
    stance: PersonalRelationship['stance'],
    roles: NpcRole[],
  ): PersonalRelationship => {
    const person = [...people.values()]
      .filter((n) => !used.has(n.id))
      .sort((a, b) => {
        const score = (n: typeof a) =>
          (roles.includes(n.role) ? 0 : 10000) +
          (stance === 'rival' && n.clan === life.clan ? 1000 : 0) +
          distance(n, life.settlement) +
          (deriveSeed(seed, stance, n.id) % 100) / 100;
        return score(a) - score(b);
      })[0];
    if (!person) throw new Error('This life needs actual inhabited neighbors.');
    used.add(person.id);
    const role = profile.roleNames[person.role];
    const reason =
      stance === 'ally'
        ? `${person.name} relied on ${life.name} over ${hook.stakes}. ${hook.reason}`
        : stance === 'witness'
          ? `${person.name}, a ${role}, retained evidence of ${cause}. Their account connects ${life.name} to ${hook.stakes}.`
          : `${person.name} represents ${profile.factions[person.clan].name} in the dispute over ${hook.stakes}. Their faction could ${motive}; their account may also expose something your friends omitted.`;
    const account =
      stance === 'ally'
        ? `I knew ${life.name} before you arrived. I asked for help over ${hook.stakes}. I still need an answer from this household.`
        : stance === 'witness'
          ? `I kept evidence of ${cause}. It bears on ${hook.stakes}. I saw ${life.name} here before the dispute.`
          : `My people have a claim to ${hook.stakes}. Ask the others why their record contains ${cause}. Their version is not the only one.`;
    return {
      npcId: person.id,
      name: person.name,
      role,
      clan: person.clan,
      stance,
      reason,
      account,
      target: { x: person.x, y: person.y },
    };
  };
  const ally = choose('ally', ['botanist', 'merchant', 'refugee']);
  const witness = choose('witness', ['archivist', 'engineer']);
  const rival = choose('rival', ['guard', 'merchant']);
  const item: ItemId =
    life.profession === 'engineer'
      ? 'wood'
      : life.profession === 'archivist' || life.profession === 'raider'
        ? 'ore'
        : life.profession === 'botanist'
          ? 'heartleaf'
          : life.profession === 'guard' || life.profession === 'merchant'
            ? 'rations'
            : 'cequin';
  const signalProp = world
    .propsAround(life.settlement.x, life.settlement.y, 12)
    .find((p) => p.kind === 'radio');
  if (!signalProp) throw new Error('An inhabited life needs its real settlement signal relay.');
  const profession = profile.roleNames[life.profession];
  return {
    id: `personal:${life.id}:${life.index}`,
    title: `${life.name}: ${hook.title.toLowerCase()}`,
    subtitle: `${profession} · ${life.settlement.name} · ${profile.eraName}`,
    worldContext: `${profile.name}. ${profile.politics.governance}. ${profile.politics.law}`,
    history: [
      {
        age: 12 + (seed % 5),
        title: [
          'An apprenticeship paid in work',
          'A trade learned under pressure',
          'The first contract kept',
        ][(seed >>> 22) % 3],
        text: `${life.name} learned the work of a ${profession} through ${profile.factions[life.clan].name}. The household remembers ${ally.name} as the person who kept that apprenticeship possible.`,
      },
      {
        age: Math.max(17, life.age - 4 - ((seed >>> 8) % 7)),
        title: ['An address earned', 'The household ledger', 'A key handed over'][
          (seed >>> 24) % 3
        ],
        text: `${life.home.name} became this person's address in ${life.settlement.name}. Its contents and responsibilities belong to the resident, rather than to the awareness that has just arrived.`,
      },
      {
        age: life.age - 1,
        title: hook.title,
        text: `${witness.name} kept evidence of ${cause}. It puts ${hook.stakes} at risk. ${rival.name} insists the case belongs to ${profile.factions[rival.clan].name}; ${ally.name} asked this household to act before the next public account.`,
      },
    ].sort((a, b) => a.age - b.age),
    relationships: [ally, witness, rival],
    debt: {
      item,
      itemName: (profile.lexicon as Partial<Record<ItemId, string>>)[item] ?? item,
      required: 3 + ((seed >>> 10) % 4),
      recipient: ally,
      title: hook.delivery,
      reason: hook.reason,
    },
    case: caseProfile,
    reward: { coins: 32 + ((seed >>> 17) % 28), xp: 35 + ((seed >>> 23) % 21) },
    commissionGoal: 2 + ((seed >>> 14) % 3),
    signal: { id: signalProp.id, name: signalProp.name, x: signalProp.x, y: signalProp.y },
    mystery: `${cause[0].toUpperCase() + cause.slice(1)} threatens ${hook.stakes}. ${witness.name} kept a trace from the time ${life.name} was ${life.activity.label.toLowerCase()}; ${rival.name} disputes who can use it.`,
    purpose: `Resolve ${hook.stakes} without surrendering the account to the interested faction. The terminal will also establish this traveler’s first independent record of arrival.`,
  };
}
export function personalStoryView(
  plan: PersonalStoryPlan,
  record: PersonalStoryRecord,
  completedCommissions: number,
  known: readonly string[] = [],
): PersonalStoryView {
  const service = Math.min(
    plan.commissionGoal,
    Math.max(0, completedCommissions - record.baselineCommissions),
  );
  const witness = plan.relationships.find((r) => r.stance === 'witness')!;
  return {
    id: plan.id,
    title: plan.title,
    subtitle: plan.subtitle,
    worldContext: plan.worldContext,
    history: structuredClone(plan.history),
    case: { ...plan.case },
    reward: { ...plan.reward },
    mystery: plan.mystery,
    purpose: plan.purpose,
    signal: { ...plan.signal },
    debt: structuredClone(plan.debt),
    relationships: plan.relationships.map((r) => ({
      ...structuredClone(r),
      met: known.includes(r.npcId),
      heard: (record.heard ?? []).includes(r.npcId),
      trusted: record.trusted === r.npcId,
    })),
    obligations: [
      {
        id: `${plan.id}:debt`,
        title: plan.debt.title,
        description: `${plan.debt.reason} Deliver ${plan.debt.required} ${plan.debt.itemName} to ${plan.debt.recipient.name}.`,
        target: plan.debt.recipient.target,
        progress: record.repaid ? 1 : 0,
        goal: 1,
        complete: record.repaid,
      },
      {
        id: `${plan.id}:trust`,
        title: `Choose who can speak for ${plan.case.kind === 'stolen-identity' ? 'this identity' : 'the claim'}`,
        description: `Speak with ${witness.name} and the people named in this life. Choose whose account you will trust; their faction will remember the choice.`,
        target: witness.target,
        progress: record.trusted ? 1 : 0,
        goal: 1,
        complete: !!record.trusted,
      },
      {
        id: `${plan.id}:standing`,
        title:
          plan.case.kind === 'shop-audit' || plan.case.kind === 'lost-research'
            ? 'Demonstrate the work behind the claim'
            : 'Earn an independent public standing',
        description: `Complete and claim ${plan.commissionGoal} local noticeboard commissions after entering this life. Supplies already in your pack do not replace the required work.`,
        target: { x: plan.signal.x - 5, y: plan.signal.y },
        progress: service,
        goal: plan.commissionGoal,
        complete: service >= plan.commissionGoal,
      },
      {
        id: `${plan.id}:signal`,
        title: `Register the ${plan.case.kind === 'broken-broadcast' ? 'recovered warning' : plan.case.kind === 'land-dispute' ? 'witnessed title' : 'independent account'}`,
        description: `After settling the promise, choosing a witness and earning local standing, align ${plan.signal.name} with one crafted lens, two ore and one timber.`,
        target: plan.signal,
        progress: record.aligned ? 1 : 0,
        goal: 1,
        complete: record.aligned,
      },
    ],
    complete: record.aligned,
  };
}

/** The first session follows this body's unfinished business. No separate quest state is saved. */
export function personalThread(
  story: PersonalStoryView,
  inventory: Partial<Record<ItemId, number>>,
  contract?: {
    title: string;
    progress: number;
    required: number;
    target: Point;
    status: string;
  } | null,
) {
  const heard = story.relationships.filter((person) => person.heard);
  if (!story.obligations[1].complete) {
    if (heard.length < 2) {
      const next = [
        story.relationships.find((person) => person.stance === 'ally'),
        story.relationships.find((person) => person.stance === 'witness'),
        story.relationships.find((person) => person.stance === 'rival'),
      ].find((person) => person && !person.heard)!;
      return {
        title: story.case.title,
        objective: `Talk to ${next.name}. Hear another account before choosing. Click to approach · E to talk.`,
        target: next.target,
        stage: 'Hear the people involved',
      };
    }
    return {
      title: story.case.title,
      objective:
        'Speak with either person again and choose an account to back. Their faction will remember.',
      target: heard[0].target,
      stage: 'Make a choice',
    };
  }
  if (!story.obligations[0].complete) {
    const debt = story.debt;
    const have = inventory[debt.item] ?? 0;
    return {
      title: debt.title,
      objective: `${have}/${debt.required} ${debt.itemName}. ${have >= debt.required ? 'Deliver to' : 'Gather or buy more, then deliver to'} ${debt.recipient.name}.`,
      target: debt.recipient.target,
      stage: 'Keep a promise',
    };
  }
  if (!story.obligations[2].complete) {
    const work = story.obligations[2];
    return {
      title: contract?.status === 'active' ? contract.title : work.title,
      objective:
        contract?.status === 'active'
          ? `${contract.progress}/${contract.required} done. Work, then report to the board for pay and standing.`
          : `${work.progress}/${work.goal} commissions claimed. Read the nearby noticeboard to choose work.`,
      target: contract?.status === 'active' ? contract.target : work.target,
      stage: 'Earn local standing',
    };
  }
  if (!story.complete)
    return {
      title: story.obligations[3].title,
      objective: `Craft a lens, then bring it with two ore and one timber to ${story.signal.name}.`,
      target: story.signal,
      stage: 'Leave an independent record',
    };
  return {
    title: 'Another life is possible',
    objective:
      'Continue this work, or enter a willing person at a quiet memorial. Knowledge travels; possessions stay.',
    target: undefined,
    stage: 'Your next life',
  };
}
export function restorePersonalStories(raw: unknown): PersonalStoriesState {
  if (raw === undefined) return { version: 1, records: [] };
  const fail = (): never => {
    throw new Error('Invalid personal life history.');
  };
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return fail();
  const state = raw as PersonalStoriesState;
  const id = (v: unknown) => typeof v === 'string' && v.length > 0 && v.length <= 160;
  if (
    state.version !== 1 ||
    !Array.isArray(state.records) ||
    state.records.length > 128 ||
    new Set(state.records.map((r) => r?.bodyId)).size !== state.records.length
  )
    return fail();
  for (const r of state.records)
    if (
      !r ||
      !id(r.bodyId) ||
      !Number.isSafeInteger(r.baselineCommissions) ||
      r.baselineCommissions < 0 ||
      r.baselineCommissions > 1e9 ||
      typeof r.repaid !== 'boolean' ||
      typeof r.aligned !== 'boolean' ||
      (r.trusted !== null && !id(r.trusted)) ||
      (r.aligned && (!r.repaid || !r.trusted)) ||
      (r.heard !== undefined &&
        (!Array.isArray(r.heard) ||
          r.heard.length > 3 ||
          new Set(r.heard).size !== r.heard.length ||
          !r.heard.every(id)))
    )
      return fail();
  return {
    version: 1,
    records: state.records.map((r) => ({ ...structuredClone(r), heard: r.heard ?? [] })),
  };
}
